function PlotAgeDO(X1, Y1, S1, C1, X2, Y2, C2, X3, Y3, C3, X4, Y4, C4, X5, Y5)
%CREATEFIGURE(X1, Y1, S1, C1, X2, Y2, C2, X3, Y3, C3, X4, Y4, C4, X5, Y5)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c
%  X2:  scatter x
%  Y2:  scatter y
%  C2:  scatter c
%  X3:  scatter x
%  Y3:  scatter y
%  C3:  scatter c
%  X4:  scatter x
%  Y4:  scatter y
%  C4:  scatter c
%  X5:  vector of x data
%  Y5:  vector of y data

%  Auto-generated by MATLAB on 10-Mar-2021 11:41:43

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,S1,C1,'DisplayName','Spring','MarkerFaceColor',[0 1 0],...
    'MarkerEdgeColor',[0 0 0]);

% Create scatter
scatter(X2,Y2,S1,C2,'DisplayName','Summer',...
    'MarkerFaceColor',[1 0.600000023841858 0.7843137383461],...
    'MarkerEdgeColor',[0 0 0]);

% Create scatter
scatter(X3,Y3,S1,C3,'DisplayName','Autumn',...
    'MarkerFaceColor',[0.749019622802734 0.749019622802734 0],...
    'MarkerEdgeColor',[0 0 0]);

% Create scatter
scatter(X4,Y4,S1,C4,'DisplayName','Winter',...
    'MarkerFaceColor',[0.678431391716003 0.921568632125854 1],...
    'MarkerEdgeColor',[0 0 0]);

% Create plot
plot(X5,Y5,'DisplayName','y = 0.0495x + 2.8607','LineWidth',2,...
    'Color',[0 0 0]);

% Create ylabel
ylabel('DO (mg/L)');

% Create xlabel
xlabel('Water Age (Day)');

box(axes1,'on');
% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 180]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 14]);
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',16,'YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southeast','FontSize',16);

