function plotTidalFlatsAge(YMatrix1)
%CREATEFIGURE1(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 09-Mar-2021 01:05:45

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'MarkerSize',10,'LineWidth',2,'Color',[0 0 0],...
    'Parent',axes1,...
    'LineStyle',':');
set(plot1(1),'DisplayName','Inner Bay','Marker','o','LineStyle','-');
set(plot1(2),'DisplayName','Sanbanze','Marker','+');
set(plot1(3),'DisplayName','Banzu','Marker','x');
set(plot1(4),'DisplayName','Futsu','Marker','*');

% Create ylabel
ylabel('Water Age Variability (Day)');

% Create xlabel
xlabel('Time');
xlim(axes1,[0 19]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 19]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-15 30]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',16,'XTick',...
    [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18],'XTickLabel',...
    {'','','Aug','','','Nov','_{2014}','','Feb','','','May','','','Aug','','','Nov','_{2015}'},...
    'YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','northwest','FontSize',16);

