function plotMonthlyAge(YMatrix1)
%CREATEFIGURE1(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 08-Mar-2021 22:53:13

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'MarkerSize',10,'LineWidth',2,'Color',[0 0 0],...
    'Parent',axes1);
set(plot1(1),'DisplayName','Surface water','Marker','^','LineStyle','-.');
set(plot1(2),'DisplayName','Middle water','Marker','o','LineStyle','--');
set(plot1(3),'DisplayName','Bottom water','Marker','v');

% Create ylabel
ylabel('Water Age (day)','FontName','Times New Roman');
% ylim(axes1,[20 70]);

% Create xlabel
xlabel('Time','FontName','Times New Roman');
xlim(axes1,[0 19]);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',16,'XTick',...
    [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18],'XTickLabel',...
    {'','Aug','','','Nov','_{2014}','','Feb','','','May','','','Aug','','','Nov','_{2015}'},...
    'YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'FontSize',16);

