function plotAgeDo2(X1, Y1, S1, C1, X2, Y2, C2, X3, Y3, C3, X4, YMatrix1)
%CREATEFIGURE(X1, Y1, S1, C1, X2, Y2, C2, X3, Y3, C3, X4, YMatrix1)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c
%  X2:  scatter x
%  Y2:  scatter y
%  C2:  scatter c
%  X3:  scatter x
%  Y3:  scatter y
%  C3:  scatter c
%  X4:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 12-Mar-2021 03:48:52

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,S1,C1,'DisplayName','Jul 1 - Jul 2, 2014',...
    'MarkerFaceColor',[0.749019622802734 0.749019622802734 0],...
    'MarkerEdgeColor',[0 0 0]);

% Create scatter
scatter(X2,Y2,S1,C2,'DisplayName','Oct 1, 2014',...
    'MarkerFaceColor',[0.494117647409439 0.184313729405403 0.556862771511078],...
    'MarkerEdgeColor',[0 0 0]);

% Create scatter
scatter(X3,Y3,S1,C3,'DisplayName','Jun 1, 2015',...
    'MarkerFaceColor',[0.301960796117783 0.745098054409027 0.933333337306976],...
    'MarkerEdgeColor',[0 0 0]);

% Create multiple lines using matrix input to plot
plot1 = plot(X4,YMatrix1,'LineWidth',2,'Parent',axes1);
set(plot1(1),'DisplayName','Jul 1 - Jul 2, 2014',...
    'Color',[0.749019622802734 0.749019622802734 0]);
set(plot1(2),'DisplayName','Oct 1, 2014',...
    'Color',[0.494117647409439 0.184313729405403 0.556862771511078]);
set(plot1(3),'DisplayName','Jun 1, 2015',...
    'Color',[0.301960796117783 0.745098054409027 0.933333337306976]);

% Create ylabel
ylabel('DO (mg/L)');

% Create xlabel
xlabel('Water Age (Day)');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 110]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 14]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',16,'YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','northwest','FontSize',16);

